
SELECT NOME, 
CASE
	WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'VELHOS'
    WHEN YEAR(DATA_DE_NASCIMENTO) BETWEEN 1990 AND 1995 THEN 'JOVENS'
    ELSE 'CRIANÇAS'
END AS 'CLASSIFICAÇÃO ETÁRIA' FROM tabela_de_clientes;