
-- Estados e suas somas de limites
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS 'SOMA DE LIMITE' FROM tabela_de_clientes
GROUP BY ESTADO;

-- Estados com maior de 900000 mil de limite
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS 'SOMA DE LIMITE' FROM tabela_de_clientes
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) > 900000;

-- Maior e monor preço por embalagem
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'MAIOR PREÇO', 
MIN(PRECO_DE_LISTA) AS 'MENOR PREÇO' FROM tabela_de_produtos
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS 'MAIOR PREÇO', 
MIN(PRECO_DE_LISTA) AS 'MENOR PREÇO' FROM tabela_de_produtos
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) < 80 AND MAX(PRECO_DE_LISTA) >= 5;